version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data 
    restart: always

  app:
    image: python:3.9-slim
    container_name: visitor_counter
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && python app.py"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always

volumes:
  redis-data:  
